version: "3"
services:
  mongo:
    image: 'mongo:5'
    volumes:
      - "/var/lib/mongo:/data/mongo_db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - '27017:27017'   
    logging:
        driver: none
    
